# the offset is how many free slots there are before a player gets kicked,
# i.e if offset is 2, an afk player will be kicked when there are only 2 slots left on server
kick-message: You were kicked because the server is almost full. Please rejoin :)
offset: 1